### ISSUE TITLE
module `neowords.rabbit-hop.api` not found

### ISSUE THREAD

**Issue by xlboy** [backdround/neowords.nvim#5]
![image](https://github.com/backdround/neowords.nvim/assets/63690944/c6ab9420-b19b-47b4-9f0e-2538d0cf2a9a)

---

```lua
-- in lazy
{
  "backdround/neowords.nvim",
  lazy = false,
  event = "BufRead",
  config = function()
    local p = require("neowords").pattern_presets
  end,
}
```

```bash
nvim -v
# NVIM v0.10.0-dev-2042+g28c183b38
# Build type: RelWithDebInfo
# LuaJIT 2.1.1703358377
# Run "nvim -V1 -v" for more info
```

**Comment by backdround** [comment]
Hello, Can you check if you have a symlink in `lazy/neowords.nvim/lua/neowords/`
![image](https://github.com/backdround/neowords.nvim/assets/17349169/f02f4545-a4a2-461e-a607-39780e2d3da6)

If you don't have, can you provide some information about your file system and git version? I want to make sure that the problem is recurrent for some people.

Sorry for your troubles.

**Comment by xlboy** [comment]
> Hello, Can you check if you have a symlink in `lazy/neowords.nvim/lua/neowords/` ![image](https://private-user-images.githubusercontent.com/17349169/294752377-f02f4545-a4a2-461e-a607-39780e2d3da6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MjQ3NzksIm5iZiI6MTcwNDYyNDQ3OSwicGF0aCI6Ii8xNzM0OTE2OS8yOTQ3NTIzNzctZjAyZjQ1NDUtYTRhMi00NjFlLWE2MDctMzk3ODBlMmQzZGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDEwNDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMGNlYzcyN2QyMjFiOWNiMjAxZGQzMGE3NmIyZjYzMzM3ZGE0MjgyMmIyMWQwZWViYTEwMWJlN2YzZTIzNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JzghnxuFULPrkAR95LzJu8Z3EzE065RV6Di0_vfgsm0)
> 
> If you don't, can you provide some information about your file system and git version? I want to make sure that the problem is recurrent for some people.
> 
> Sorry for your troubles.

**git version**: `git version 2.43.0.windows.1`

**windows system version:** `Windows 10 - 22H2`

---
I'm sorry, I just messed with it, but it seems that symbolic links in this way can not be handled correctly in windows environment (uncertain)

**Comment by backdround** [comment]
I've just gotten rid of symlinks. It should work now.

As I figured it out, symlinks work on windows, but with additional requirements:
- Git should be configured to `core.symlinks true`
- Developer mode should be enabled
- Git should be executed with elevated permissions (Run as administrator)

**Comment by xlboy** [comment]
> I've just gotten rid of symlinks. It should work now.
> 
> As I figured it out, symlinks work on windows, but with additional requirements:
> 
> * Git should be configured to `core.symlinks true`
> * Developer mode should be enabled
> * Git should be executed with elevated permissions (Run as administrator)

Haha, this requirement is still a bit high

Please wait a moment, I will try to give it a try

**Comment by xlboy** [comment]
It is running well now, thank you very much for your contribution!

**Comment by backdround** [comment]
Nice!
